#!/usr/bin/env python3
import hashlib
import os
import shutil

FIGURES = [
    ("physics/artifacts/smoke_core.png", "physics/tex/figures/smoke_core.png"),
    ("physics/artifacts/quantum_dpi_hist.png", "physics/tex/figures/quantum_dpi_hist.png"),
    ("physics/artifacts/quantum_closure_idempotence.png", "physics/tex/figures/quantum_closure_idempotence.png"),
    ("physics/artifacts/quantum_route_mismatch.png", "physics/tex/figures/quantum_route_mismatch.png"),
    ("physics/artifacts/bgk_idempotence_defect.png", "physics/tex/figures/bgk_idempotence_defect.png"),
    ("physics/artifacts/bgk_failure_modes.png", "physics/tex/figures/bgk_failure_modes.png"),
    ("physics/artifacts/les_route_mismatch.png", "physics/tex/figures/les_route_mismatch.png"),
    ("physics/artifacts/les_subgrid_term.png", "physics/tex/figures/les_subgrid_term.png"),
    ("physics/artifacts/gravity_backreaction.png", "physics/tex/figures/gravity_backreaction.png"),
    ("physics/artifacts/gravity_packaging_mismatch.png", "physics/tex/figures/gravity_packaging_mismatch.png"),
]


def repo_root() -> str:
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def macro_name(filename: str) -> str:
    base = os.path.splitext(os.path.basename(filename))[0]
    parts = base.split("_")
    return "fig" + "".join(p.capitalize() for p in parts)


def main() -> None:
    root = repo_root()
    manifest_path = os.path.join(root, "physics", "tex", "autogen", "figures_manifest.tex")
    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)

    for src_rel, dst_rel in FIGURES:
        src = os.path.join(root, src_rel)
        if not os.path.exists(src):
            raise SystemExit(f"Missing source figure: {src_rel}")

    entries = []
    for src_rel, dst_rel in FIGURES:
        src = os.path.join(root, src_rel)
        dst = os.path.join(root, dst_rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
        h = sha256_file(dst)
        entries.append((dst_rel, h))

    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write("% Generated by physics/python/export_figures_for_tex.py\n")
        for dst_rel, h in entries:
            base = os.path.basename(dst_rel)
            f.write(f"% {base} sha256: {h}\n")
            f.write(f"\\newcommand{{\\{macro_name(base)}}}{{figures/{base}}}\n")

    for _, dst_rel in FIGURES:
        print(os.path.basename(dst_rel))


if __name__ == "__main__":
    main()
